version: 2.1

workflows:
  build-and-deploy:
    jobs:
      - run-me

jobs:
  run-me:
    machine: true
    resource_class: ng0cth1nh/demo-server-1
    steps:
      - run:
          name: Clone git repository
          command: git clone https://github.com/ng0cth1nh/demo-go.git -b $CIRCLE_BRANCH .
      - run:
          name: Check podman
          command: podman version
      - run:
          name: Build
          command: podman --cgroup-manager cgroupfs build . -t http://docker-registry.chop.dev:5000/demo-go:$CIRCLE_BRANCH
      - run:
          name: Push to docker registry
          command: podman --cgroup-manager cgroupfs push http://docker-registry.chop.dev:5000/demo-go:$CIRCLE_BRANCH
